/* Database schema to keep the structure of entire database. */

CREATE TABLE IF NOT EXISTS animals (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts INT NOT NULL,
    neutered BOOLEAN NOT NULL,
    weight_kg FLOAT NOT NULL
);

-- Add a new column species to the animals table
ALTER TABLE animals ADD COLUMN species VARCHAR(100);

-- Create table owners
CREATE TABLE IF NOT EXISTS owners (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    age INT NOT NULL
);

-- Create table species
CREATE TABLE IF NOT EXISTS species (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- Modify animals table:
--    Make sure that id is set as autoincremented PRIMARY KEY
--    Remove column species
--    Add column species_id which is a foreign key referencing species table
--    Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE animals ADD PRIMARY KEY (id);
ALTER TABLE animals 
    DROP COLUMN species, 
    ADD COLUMN species_id INT REFERENCES species(id),
    ADD COLUMN owner_id INT REFERENCES owners(id);
